//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int FlightNumber { get; set; }
        public int RouteID { get; set; }
        public System.DateTime FlightDate { get; set; }
        public int CurrentPassengers { get; set; }
        public int MaxPassengers { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
