//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.Transactions = new ObservableListSource<Transaction>();
            this.Flights = new ObservableListSource<Flight>();
        }
    
        public int RouteID { get; set; }
        public int OriginCityID { get; set; }
        public int DestinationCityID { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public Nullable<int> Stop1CityID { get; set; }
        public Nullable<System.DateTime> Stop1ArrivalTime { get; set; }
        public Nullable<System.DateTime> Stop1DepartureTime { get; set; }
        public Nullable<int> Stop2CityID { get; set; }
        public Nullable<System.DateTime> Stop2ArrivalTime { get; set; }
        public Nullable<System.DateTime> Stop2DepartureTime { get; set; }
        public int AirplaneID { get; set; }
        public decimal TicketPrice { get; set; }
        public int PointsAwarded { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Flight> Flights { get; set; }
    }
}
