//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int FlightNumber { get; set; }
        public int RouteID { get; set; }
        public System.DateTime Date { get; set; }
        public byte PaymentType { get; set; }
        public int UserID { get; set; }
        public byte StatusType { get; set; }
    
        public virtual Route Route { get; set; }
        public virtual User User { get; set; }
    }
}
