//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAirlines
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Transactions = new ObservableListSource<Transaction>();
        }
    
        public int UserID { get; set; }
        public byte UserType { get; set; }
        public string FullName { get; set; }
        public byte[] PasswordHash { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string PhoneNumber { get; set; }
        public short Age { get; set; }
        public string CardNumber { get; set; }
        public System.DateTime CardExpiryDate { get; set; }
        public short CardCVV { get; set; }
        public int PointsAvailable { get; set; }
        public int PointsRedeemed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Transaction> Transactions { get; set; }
    }
}
